name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        rake docker_images
        rake docker_test
